app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('download/', views.pullData, name='download'),
    path('downloadDocumentation/', views.downloadDocumentation, name='downloadDocumentation'),
    path('upload/', views.pushData, name='upload_file'),
    path('send/', views.Email, name='email'),
    path('sendEmails/', views.SendEmails, name='send'),
    path('register/', views.Register, name='register'),
    path('test/', views.Test, name='test'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('insert/', views.DemonstratorInsert2, name='insert'),
    path('query/', views.QueryDemonstrator, name='query'),
    path('allDemonstrators/', views.getAllDemonstrators, name='allDemonstrators'),
    path('demonstrator/<int:id>/', views.getDemonstrator, name='demonstrator'),
    path('dispatch/<int:demonId>/', views.DispatchInsert, name='dispatch'),
    path('getdispatch/<int:dispatchId>/', views.getDispatch, name='getdispatch'),
    path('extinsert/<int:dispatchId>/<int:demonId>/', views.ExtensionInsert, name='extinsert'),
    path('extensionEmail/<int:dispatchId>/<int:demonId>/<int:extensionId>/', views.SendExtensionEmail, name='extensionEmail'),
    path('freinsert/<int:dispatchId>/<int:demonId>/', views.FreezeInsert, name='freinsert'),
    path('reportinsert/<int:dispatchId>/<int:demonId>/', views.ReportInsert, name='reportinsert'),
    path('updateExtension/<int:id>/<int:demonId>/', views.UpdateExtension, name='updateExtension'),
    path('updateFreeze/<int:id>/<int:demonId>/', views.UpdateFreeze, name='updateFreeze'),
    path('updateDispatch/<int:id>/<int:demonId>/', views.UpdateDispatch, name='updateDispatch'),
    path('updateUnv/<int:id>/<int:demonId>/', views.UpdateUniversityDegree, name='updateUnv'),
    path('updateGrad/<int:id>/<int:demonId>/', views.UpdateGraduateStudies, name='updateGrad'),
    path('updateDemon/<int:id>/', views.UpdateDemonstrator, name='updateDemon'),
    path('deleteExtension/<int:id>/<int:demonId>/', views.DeleteExtension, name='deleteExtension'),
    path('deleteFreeze/<int:id>/<int:demonId>/', views.DeleteFreeze, name='deleteFreeze'),
    path('deleteDispatch/<int:id>/<int:demonId>/', views.DeleteDispatch, name='deleteDispatch'),
    path('deleteUnv/<int:id>/<int:demonId>/', views.DeleteUniversityDegree, name='deleteUnv'),
    path('deleteGrad/<int:id>/<int:demonId>/', views.DeleteGraduateStudies, name='deleteGrad'),
    path('deleteCert/<int:id>/<int:demonId>/', views.DeleteCertificateOfExcellence, name='deleteCert'),
    path('deleteDemon/<int:id>/', views.DeleteDemonstrator, name='deleteDemon'),
    path('getAllEmails/', views.GetAllEmails, name='getAllEmails'),
    path('getLateEmails/', views.GetLateEmails, name='getLateEmails'),
    path('getCollegeEmails/', views.GetCollegeEmails, name='getCollegeEmails'),
    path('reportinsert/<int:demonId>/', views.GraduateStudiesDegreeInsert, name='insertGraduate'),
    path('insertExcellence/<int:demonId>/', views.CertificateExcellenceYearInsert, name='insertExcellence'),
    path('durationInsert/<int:dispatchId>/<int:demonId>/', views.DurationChangeInsert, name='durationInsert'),
    path('getAllUsers/', views.GetAllUsers, name='getAllUsers'),
    path('gett/', views.do_something, name='gett'),
    path('test/', views.Test, name='test'),
    path('permissions/', views.permissions_list, name='permissions_list'),
    path('permissions/<int:pk>/', views.permissions_detail, name='permissions_detail'),
    path('permissions/delete/<int:pk>/', views.DeletePermission, name='permissions_delete'),
    path('permissions/update/<int:pk>/', views.UpdatePermission, name='permissions_update'),
    path('permissions/insert/', views.PermissionInsert, name='permissions_insert'),
    path('users/', views.GetAllUsers, name='user_list'),
    path('users/<int:id>', views.GetUser, name='permissions_insert'),
    path('users/update/<int:id>', views.UpdateUser, name='permissions_insert'),
    path('users/delete/<int:id>', views.DeleteUser, name='permissions_insert'),
    path('users/changePassword/<int:id>', views.UpdateUserPassword, name='permissions_insert'),
    path('users/makeUserAdmin/<int:id>', views.MakeUserAdmin, name='permissions_insert'),
    path('about-us', views.About, name='about_us'),


]

projectFifthYear/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls', namespace='app'),),
    path('', views.goToHome, name='goToHome'),
    
]
#re_path('', RedirectView.as_view(url='app', permanent=False), name='index'),

app/forms.py
from django.forms import ModelForm
from .models import *
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()
    
    
class AddUser(ModelForm):
    class Meta:
        model= User
        exclude=[]
    
    
class AddUserSynchronization(ModelForm):
    class Meta:
        model= UserSynchronization
        exclude=[]


class AddPermissions(ModelForm):
    class Meta:
        model= Permissions
        exclude = []


class AddDemonstrator(ModelForm):
    class Meta:
        model = Demonstrator
        exclude = []


class AddUniversityDegree(ModelForm):
    class Meta:
        model = UniversityDegree
        exclude = []


class AddNomination(ModelForm):
    class Meta:
        model = Nomination
        exclude = []


class AddAdjectiveChange(ModelForm):
    class Meta:
        model = AdjectiveChange
        exclude = []


class AddCertificateOfExcellence(ModelForm):
    class Meta:
        model = CertificateOfExcellence
        exclude = []


class AddGraduateStudies(ModelForm):
    class Meta:
        model = GraduateStudies
        exclude = []


class AddDispatch(ModelForm):
    class Meta:
        model = Dispatch
        exclude = []


class AddReport(ModelForm):
    class Meta:
        model = Report
        exclude = []


class AddRegularization(ModelForm):
    class Meta:
        model = Regularization
        exclude = []


class AddExtension(ModelForm):
    class Meta:
        model = Extension
        exclude = []


class AddFreeze(ModelForm):
    class Meta:
        model = Freeze
        exclude = []


class AddDurationChange(ModelForm):
    class Meta:
        model = DurationChange
        exclude = []


class AddAlimonyChange(ModelForm):
    class Meta:
        model = AlimonyChange
        exclude = []


class AddUniversityChange(ModelForm):
    class Meta:
        model = UniversityChange
        exclude = []


class AddSpecializationChange(ModelForm):
    class Meta:
        model = SpecializationChange
        exclude = []


class AddDeletedObjects(ModelForm):
    class Meta:
        model = DeletedObjects
        exclude = []

templates/home/allDemonstrators.html
{% extends "base.html" %} {% block head_title %}المعيدين{% endblock %}

<!-- something here for nothing  -->
{% load static %} {% block content %}
<h2 class="tit">جميع المعيدين</h2>
<section class="sec">
  <data-table src="{{result}} "></data-table>
</section>

{% block files %}
<script src="{% static 'js/table.js' %}" type="module"></script>
{% endblock %} {% endblock %}

templates/home/home.html
{% extends "base.html" %} {% block head_title %}الصفحة الرئيسية{% endblock %}
<!-- something not usefull -->
{% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'css/home.css'%}" />
<link rel="stylesheet" href="{% static 'css/skydash/css/vertical-layout-light/style.css'%}" />
<style type="text/css">
  /* Chart.js */
  @keyframes chartjs-render-animation {
    from {
      opacity: .99
    }

    to {
      opacity: 1
    }
  }

  .chartjs-render-monitor {
    animation: chartjs-render-animation 1ms
  }

  .chartjs-size-monitor,
  .chartjs-size-monitor-expand,
  .chartjs-size-monitor-shrink {
    position: absolute;
    direction: ltr;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    overflow: hidden;
    pointer-events: none;
    visibility: hidden;
    z-index: -1
  }

  .chartjs-size-monitor-expand>div {
    position: absolute;
    width: 1000000px;
    height: 1000000px;
    left: 0;
    top: 0
  }

  .chartjs-size-monitor-shrink>div {
    position: absolute;
    width: 200%;
    height: 200%;
    left: 0;
    top: 0
  }
</style>
<script src="{% static 'js/chart.js' %}">

</script>
{% endblock %}
{%block content %}

<h2 class="tit">الصفحة الرئيسية</h2>


<div class="row align-items-center">
  <div class="col-md-6 grid-margin stretch-card">
    <div class="card tale-bg">
      <div class="card-people mt-auto">
        <img src="{% static 'images/people.svg' %}" alt="people">
        <div class="weather-info">
          <div class="d-flex">

            <div class="ml-2">
              <h4 class="location font-weight-normal">سوريا</h4>
              <h6 class="font-weight-normal">حمص</h6>
            </div>
            <div>
              <h2 class="mb-0 font-weight-normal"><i class="fa-solid fa-calender  mr-2"></i><span id="dd"></span></h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 grid-margin transparent">
    <div class="row">
      <div class="col-md-6 mb-4 stretch-card transparent">
        <div class="card card-dark-blue">
          <div class="card-body">
            <p class="mb-4">العدد الكلي</p>
            <p class="fs-30 mb-2">{{statistics.allDemons}}</p>

          </div>
        </div>
      </div>
      <div class="col-md-6 mb-4 stretch-card transparent">
        <div class="card card-tale">
          <div class="card-body">
            <p class="mb-4">عدد المعيدين</p>
            <p class="fs-30 mb-2">{{statistics.allInDispatch}}</p>

          </div>
        </div>
      </div>

    </div>
    <div class="row">
      <div class="col-md-6 stretch-card transparent">
        <div class="card card-light-danger">
          <div class="card-body">
            <p class="mb-4">الماجستير</p>
            <p class="fs-30 mb-2">{{statistics.master}}</p>

          </div>
        </div>
      </div>
      <div class="col-md-6 mb-4 mb-lg-0 stretch-card transparent">
        <div class="card card-light-blue">
          <div class="card-body">
            <p class="mb-4">الدكتوراه</p>
            <p class="fs-30 mb-2">{{statistics.phd}}</p>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>


<div class="row justify-content-center">
  <div class="col-lg-10 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div class="chartjs-size-monitor">
          <div class="chartjs-size-monitor-expand">
            <div class=""></div>
          </div>
          <div class="chartjs-size-monitor-shrink">
            <div class="barChart"></div>
          </div>
        </div>
        <h4 class="card-title">إحصائيات المعيدين </h4>
        <canvas id="myChart" style="display: inline; height: 274px; width: 549px;" width="686" height="342"></canvas>
      </div>
    </div>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-md-10 justify-content-center grid-margin stretch-card">
    <div class="card row" style='background: inherit'>
      <div class="card-body row justify-content-around cardss">
        {% if user.is_superuser %}
        <div class="col-5 mb-3">
          <div class="card card-inverse-light border-dark mb-3 mx-auto" style="background-color:#ffffff;">
            <h5 class="card-header">
              <i class="fa-solid fa-user-tie"></i>
              <span class="mr-3"> لائحة الموظفين</span>
            </h5>
            <div class="card-body text-dark">
              <p class="card-text">
              <div class="intro-button mx-auto row justify-content-between align-items-center"> <span class="col-8"> قم
                  بتسجيل موظف جديد للعمل في إدارة العلاقات الثقافية</span><a class="btn btn-primary btn-xl col-2 "
                  href="{% url 'app:user_list' %}"><i class="fa-solid fa-arrow-left"></i></a></div>
              </p>
            </div>
          </div>
        </div>
        <div class="col-5 mb-3">
          <div class="card card-inverse-light border-dark mb-3 mx-auto" style="background-color:#ffffff;">
            <h5 class="card-header">
              <i class="fa-solid fa-server"></i>
              <span class="mr-3">لائحة السماحيات</span>
            </h5>
            <div class="card-body text-dark">
              <p class="card-text">
              <div class="intro-button mx-auto row justify-content-between align-items-center"> <span class="col-8">قم
                  بإضافة السماحيات و تعديلها و تعديل بيانات الموظفين</span><a class="btn btn-primary btn-xl col-2 "
                  href="/app/permissions"><i class="fa-solid fa-arrow-left"></i></a></div>
              </p>
            </div>
          </div>
        </div>
        {% endif %}
        <div class="col-5 mb-3">
          <div class="card card-inverse-light border-dark mb-3 mx-auto" style="background-color:#ffffff;">
            <h5 class="card-header">
              <i class="fa-solid fa-user-graduate"></i>
              <span class="mr-3"> تسجيل معيد</span>
            </h5>
            <div class="card-body text-dark">
              <p class="card-text">
              <div class="intro-button mx-auto row justify-content-between align-items-center"> <span class="col-8">قم
                  بإدخال بيانات معيد جديد</span><a class="btn btn-primary btn-xl col-2 "
                  href="{% url 'app:insert' %}"><i class="fa-solid fa-arrow-left"></i></a></div>
              </p>
            </div>
          </div>
        </div>

        <div class="col-5 mb-3">
          <div class="card card-inverse-light border-dark mb-3 mx-auto" style="background-color:#ffffff;">
            <h5 class="card-header">
              <i class="fa-solid fa-users"></i>
              <span class="mr-3"> المعيدين</span>
            </h5>
            <div class="card-body text-dark">
              <p class="card-text">
              <div class="intro-button mx-auto row justify-content-between align-items-center"> <span class="col-8">حميع
                  المعيدين المسجلين و البحث عنهم</span><a class="btn btn-primary btn-xl col-2 "
                  href="{% url 'app:allDemonstrators' %}"><i class="fa-solid fa-arrow-left"></i></a></div>
              </p>
            </div>
          </div>
        </div>
        <div class="col-5 mb-3">
          <div class="card card-inverse-light border-dark mb-3 mx-auto" style="background-color:#ffffff;">
            <h5 class="card-header">
              <i class="fa-solid fa-filter"></i>
              <span class="mr-3"> استعلام</span>
            </h5>
            <div class="card-body text-dark">
              <p class="card-text">
              <div class="intro-button mx-auto row justify-content-between align-items-center"> <span class="col-8"> قم
                  بالاستعلام عن المعيدين</span><a class="btn btn-primary btn-xl col-2 "><i
                    class="fa-solid fa-arrow-left" href="{% url 'app:gett' %}"></i></a></div>
              </p>
            </div>
          </div>
        </div>
        <div class="col-5 mb-3">
          <div class="card card-inverse-light border-dark mb-3 mx-auto" style="background-color:#ffffff;">
            <h5 class="card-header">
              <i class="fa-solid fa-envelope"></i>
              <span class="mr-3">إرسال إيميل</span>
            </h5>
            <div class="card-body text-dark">
              <p class="card-text">
              <div class="intro-button mx-auto row justify-content-between align-items-center"> <span class="col-8">قم
                  بإرسال إيميلات للمعيدين</span><a class="btn btn-primary btn-xl col-2 " href="{% url 'app:email' %}"><i
                    class="fa-solid fa-arrow-left"></i></a></div>
              </p>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>





<script>

  let data = {
    labels: ["معيد", "عائد", "موفد", "معيد عائد", "مستنكف", "نقل خارج الجامعة", "إنهاء خدمات", "مستقيلٍ"],
    datasets: [{
      data: ["{{statistics.demonstrator}}", "{{statistics.returning}}", "{{statistics.envoy}}", "{{statistics.returning_demonstrator}}", "{{statistics.loathes}}", "{{statistics.transfer_outside_the_university}}", "{{statistics.end_services}}", "{{statistics.resigned}}"],
      label: '# من المعيدين',
      base: 0,
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)',
        'rgba(165, 165, 165, 0.2)',
        'rgba(46, 58, 35, 0.2)'
      ],
      borderColor: [
        'rgba(255,99,132,1)',
        'rgba(54, 162, 235, 1)',
        'rgba(255, 206, 86, 1)',
        'rgba(75, 192, 192, 1)',
        'rgba(153, 102, 255, 1)',
        'rgba(255, 159, 64, 1)',
        'rgba(165, 165, 165, 1)',
        'rgba(46, 58, 35, 1)'
      ],
      categoryPercentage: 1,
      borderWidth: 1,
      fill: false
    }]


  }

  new Chart("myChart", {
    type: "bar",
    data: data,
    options: {
      legend: { display: false },
      title: {
        display: true,

      }
    }
  });
</script>

<script>


  let partsGre = new Intl.DateTimeFormat('ar-US', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  }).formatToParts(Date.now());
  let stringTime = ""
  partsGre.forEach(part => {
    if (part.type != 'literal') {
      stringTime += part.value + " "
    }
  });
  $("#dd").text(stringTime)
  console.log(stringTime);
</script>




{% endblock %}

templates/home/permissions_detail.html
{% extends 'base.html' %}

{% block head_title %}
{{permissions.permissionsCollege}}
{% endblock %}

{% load static %}

{% block style %}

<style>
    .mbt-ol {
        width: 300px;
        margin: 10px;
        counter-reset: my-counter;
        padding-right: 0;
    }

    .mbt-ol li {

        border-bottom: 1px dotted #ccc;
        padding: 5px;
        counter-increment: my-counter;
        list-style: none;
        margin-right: 15px
    }

    .ut {
        margin-right: 10px;
    }

    .mbt-ol li:before {
        content: counter(my-counter) ". ";
        font-weight: bold;
    }

    .sect {
        margin: 50px;
        height: 100vh;
        padding: 50px 40px;
    }
</style>

<link rel="stylesheet" href="{% static 'css/multi-select.min.css' %}">
{% endblock %}


{% block content %}

<div class="sec sect">

    <div class="row">
        <div class="col-6">
            <h1 class="mb-4">القسم: {{ permissions.permissionsCollege }}</h1>
        </div>
        <div class="col-6 d-flex justify-content-end">
            <div>

                <button class="btn btn btn-outline-success" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">تعديل</button>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">تعديل القسم</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'app:permissions_update' permissions.id %}" id="form" method="POST">
                        {% csrf_token %}
                        <div class="form-floating">
                            <input type="text" class="form-control" value="{{ permissions.permissionsCollege }}"
                                name="permissionsCollege" placeholder="asdf" id="t">
                            <label for="t">القسم</label>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">إغلاق</button>
                    <button type="submit" form="form" class="btn btn-outline-success">تعديل</button>
                </div>
            </div>
        </div>
    </div>



    <p class="fs-5 mb-3 ut">موظفوا القسم</p>
    <ol class="mbt-ol mb-4">
        {% for user in users %}
        {% if not user.is_superuser %}
        <li>{{ user.username }}</li>
        {% endif %}
        {% endfor %}
    </ol>

    <h3 class="mb-4 fs-3">اختر الموظفين:</h3>
    <div class="row">
        <div class="col-6">

            <form method="post">
                {% csrf_token %}
                <div class=" mb-3 autocomplete">
                    <select id="floatingP" name="userId" placeholder="nothing" class="form-select" multiple />

                    <label for="floatingP">القسم </label>
                    </select>
                </div>

                <br>
                <button type="submit" class="btn btn-outline-primary">حفظ</button>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'js/multi-select.js'%}"></script>

<script>
    $(document).ready(function () {
        let op
        let select = document.getElementById("floatingP");
        "{% for user in all_users %}"
        "{% if not user.is_superuser %}"
        op = document.createElement("option")
        op.value = "{{user.pk}}"
        op.text = "{{user}}"
        "{% if user in users %}"
        op.selected = true
        "{% endif %}"
        select.add(op)
        "{% endif %}"
        "{% endfor %}"







        new MultiSelectTag('floatingP')

    });
</script>
{% endblock %}



{% block styles %}
<style>
    h1 {
        font-size: 2.5rem;
        margin-bottom: 1rem;
    }

    p {
        font-size: 1.2rem;
        margin-bottom: 0.5rem;
    }

    select {
        font-size: 1.2rem;
        padding: 0.5rem;
        margin-bottom: 1rem;
    }

    button {
        font-size: 1.2rem;
        padding: 0.5rem 1rem;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 0.25rem;
        cursor: pointer;
    }
</style>
{% endblock %}

templates/home/permissions_list.html
{% extends 'base.html' %}


{% block head_title %}
لائحة الأقسام
{% endblock %}


{% block style %}

<style>
    .sect {
        margin: 50px;
        height: 100vh;
        padding: 50px 40px;
    }

    a {
        color: black
    }
</style>

{% endblock %}

{% block content %}
<div class="sec sect">

    <div class="row">
        <div class="col-6">
            <h1 class="mb-5">الأقسام</h1>
        </div>
        <div class="col-6 d-flex justify-content-end">
            <div>

                <button class="btn btn btn-outline-primary" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">إضافة</button>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">إضافة قسم</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'app:permissions_insert' %}" id="form" method="POST">
                        {% csrf_token %}
                        <div class="form-floating">
                            <input type="text" class="form-control" name="permissionsCollege" placeholder="asdf" id="t">
                            <label for="t">القسم</label>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">إغلاق</button>
                    <button type="submit" form="form" class="btn btn-outline-primary">إضافة</button>
                </div>
            </div>
        </div>
    </div>
    <form method="GET">
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1"><i
                    class="fa-sharp fa-solid fa-magnifying-glass"></i></span>
            <input type="text" name="search" class="form-control" {% if query %} value="{{query}}" {% endif %}
                placeholder="ابحث عن القسم">


            <button type="submit" class="btn btn-outline-secondary">بحث</button>

        </div>
    </form>
    <div class="list-group list-group-flush rounded">
        {% for permissions in permissions %}
        <li class="list-group-item mb-1 d-flex justify-content-between align-items-start">
            <div>
                <a href="{% url 'app:permissions_detail' permissions.pk %}">{{permissions.permissionsCollege }}</a>
            </div>
            <a href="{% url 'app:permissions_delete' permissions.pk %}">
                <span class="badge bg-danger rounded-pill"><i class="fa-solid   fa-trash"></i></span>
            </a>
        </li>
        {% empty %}
        <p>لا يوجد أقسام بعد</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/home/show-dispatch.html
{% extends "base.html" %} {% block head_title %} {{demonstrator.name}}
{%endblock %}

<!-- something here for nothing  -->
{% load static %} {% block content %}
<h2>something</h2>
<div class="sec">{{dispatch}}</div>

{% endblock %}

templates/home/success.html
{% extends "base.html" %} {% block head_title %}تم الإرسال{% endblock %}

<!-- something here for nothing  -->
{% load static %}

{% block style %}
<style>
    .success-inner {
        display: inline-block;
    }

    .success-inner h1 {
        font-size: 120px;
        text-shadow: 3px 5px 2px #3333;
        color: #006DFE;
        font-weight: 700;
        margin-bottom: 20px;
    }

    .success-inner h1 span {
        display: block;
        font-size: 25px;
        color: #333;
        font-weight: 600;
        text-shadow: none;
        margin-top: 20px;
    }

    .success-inner p {
        font-size: 1.2rem;
        padding: 5px 15px;
    }

    .success-inner .btn {
        color: #fff;
    }
</style>
{% endblock %}
<!-- something here for nothing  -->

{% block content %}

<div class="text-center h-100 sec pt-5">

    <div class="row">
        <div class="col-lg-6 offset-lg-3 col-12">
            <!-- Error Inner -->
            <div class="success-inner">
                <h1><i class="fa fa-envelope"></i><span>تم إرسال الإيميلات بنجاح</span></h1>
                {% for i in emails %}
                <p>{{i}}</p>
                {% endfor %}
                <a href="/app/" class="btn btn-primary btn-lg mt-5">عد للصفحة الرئيسية </a>
            </div>
            <!--/ End Error Inner -->
        </div>
    </div>

</div>


{% endblock %}

templates/home/upload.html
{% extends "base.html" %} {% block head_title %} إرسال إيميل{% endblock %}
{% load static %}
<!-- something here for nothing  -->

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <form method="post" enctype="multipart/form-data">

        <p class="h3 m-3">اختر ملف للتصدير</p>

        <div class="input-group">
            <label class="input-group-text" for="id_file">الملف:</label>
            <input type="file" class="form-control" name="file" required="" id="id_file">
        </div>

        <button type="submit" class="btn btn-primary mt-5">تصدير</button>
    </form>

</form>

{% endblock %}